// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package dbgen

import (
	"context"
)

const countLiveDenials = `-- name: CountLiveDenials :one
SELECT COUNT(*) FROM mirror_deny WHERE expires_at > ?
`

func (q *Queries) CountLiveDenials(ctx context.Context, expiresAt int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveDenials, expiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveGrants = `-- name: CountLiveGrants :one
SELECT COUNT(*) FROM mirror_grant
WHERE principal = ? AND resource = ? AND key = ? AND expires_at > ?
`

type CountLiveGrantsParams struct {
	Principal string
	Resource  string
	Key       string
	ExpiresAt int64
}

// Every read filters on expiry, so an expired row is unreadable the moment it
// expires rather than the moment a prune gets to it.
func (q *Queries) CountLiveGrants(ctx context.Context, arg CountLiveGrantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveGrants,
		arg.Principal,
		arg.Resource,
		arg.Key,
		arg.ExpiresAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDenial = `-- name: DeleteDenial :execrows
DELETE FROM mirror_deny WHERE principal = ? AND resource = ? AND key = ?
`

type DeleteDenialParams struct {
	Principal string
	Resource  string
	Key       string
}

func (q *Queries) DeleteDenial(ctx context.Context, arg DeleteDenialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDenial, arg.Principal, arg.Resource, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteGrantsBySource = `-- name: DeleteGrantsBySource :execrows
DELETE FROM mirror_grant WHERE principal = ? AND resource = ? AND source = ?
`

type DeleteGrantsBySourceParams struct {
	Principal string
	Resource  string
	Source    string
}

// Replace-sync: a list answer states the whole set this source knows about, so
// what it no longer names is gone rather than merged with.
func (q *Queries) DeleteGrantsBySource(ctx context.Context, arg DeleteGrantsBySourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGrantsBySource, arg.Principal, arg.Resource, arg.Source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDenial = `-- name: GetDenial :one
SELECT status FROM mirror_deny
WHERE principal = ? AND resource = ? AND key = ? AND expires_at > ?
`

type GetDenialParams struct {
	Principal string
	Resource  string
	Key       string
	ExpiresAt int64
}

func (q *Queries) GetDenial(ctx context.Context, arg GetDenialParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDenial,
		arg.Principal,
		arg.Resource,
		arg.Key,
		arg.ExpiresAt,
	)
	var status int64
	err := row.Scan(&status)
	return status, err
}

const listDenialsByPrincipal = `-- name: ListDenialsByPrincipal :many
SELECT resource, key, status, expires_at FROM mirror_deny
WHERE principal = ? AND expires_at > ? ORDER BY resource, key LIMIT ?
`

type ListDenialsByPrincipalParams struct {
	Principal string
	ExpiresAt int64
	Limit     int64
}

type ListDenialsByPrincipalRow struct {
	Resource  string
	Key       string
	Status    int64
	ExpiresAt int64
}

func (q *Queries) ListDenialsByPrincipal(ctx context.Context, arg ListDenialsByPrincipalParams) ([]ListDenialsByPrincipalRow, error) {
	rows, err := q.db.QueryContext(ctx, listDenialsByPrincipal, arg.Principal, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDenialsByPrincipalRow
	for rows.Next() {
		var i ListDenialsByPrincipalRow
		if err := rows.Scan(
			&i.Resource,
			&i.Key,
			&i.Status,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantPrincipals = `-- name: ListGrantPrincipals :many
SELECT principal, COUNT(*) AS grants, MAX(expires_at) AS newest
FROM mirror_grant WHERE expires_at > ? GROUP BY principal ORDER BY grants DESC LIMIT ?
`

type ListGrantPrincipalsParams struct {
	ExpiresAt int64
	Limit     int64
}

type ListGrantPrincipalsRow struct {
	Principal string
	Grants    int64
	Newest    interface{}
}

// The dashboard reports each principal's standing. Grants and denials are the
// only per-caller tables, so this is the whole of what the mirror knows about
// who has proven what.
func (q *Queries) ListGrantPrincipals(ctx context.Context, arg ListGrantPrincipalsParams) ([]ListGrantPrincipalsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrantPrincipals, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantPrincipalsRow
	for rows.Next() {
		var i ListGrantPrincipalsRow
		if err := rows.Scan(&i.Principal, &i.Grants, &i.Newest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsByPrincipal = `-- name: ListGrantsByPrincipal :many
SELECT resource, key, source, expires_at FROM mirror_grant
WHERE principal = ? AND expires_at > ? ORDER BY resource, key LIMIT ?
`

type ListGrantsByPrincipalParams struct {
	Principal string
	ExpiresAt int64
	Limit     int64
}

type ListGrantsByPrincipalRow struct {
	Resource  string
	Key       string
	Source    string
	ExpiresAt int64
}

func (q *Queries) ListGrantsByPrincipal(ctx context.Context, arg ListGrantsByPrincipalParams) ([]ListGrantsByPrincipalRow, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsByPrincipal, arg.Principal, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrantsByPrincipalRow
	for rows.Next() {
		var i ListGrantsByPrincipalRow
		if err := rows.Scan(
			&i.Resource,
			&i.Key,
			&i.Source,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDenials = `-- name: PruneDenials :execrows
DELETE FROM mirror_deny WHERE expires_at <= ?
`

func (q *Queries) PruneDenials(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneDenials, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneGrants = `-- name: PruneGrants :execrows
DELETE FROM mirror_grant WHERE expires_at <= ?
`

func (q *Queries) PruneGrants(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneGrants, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordDenial = `-- name: RecordDenial :exec
INSERT INTO mirror_deny (principal, resource, key, status, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (principal, resource, key) DO UPDATE SET
	status     = excluded.status,
	expires_at = excluded.expires_at
`

type RecordDenialParams struct {
	Principal string
	Resource  string
	Key       string
	Status    int64
	ExpiresAt int64
}

func (q *Queries) RecordDenial(ctx context.Context, arg RecordDenialParams) error {
	_, err := q.db.ExecContext(ctx, recordDenial,
		arg.Principal,
		arg.Resource,
		arg.Key,
		arg.Status,
		arg.ExpiresAt,
	)
	return err
}

const recordGrant = `-- name: RecordGrant :exec
INSERT INTO mirror_grant (principal, resource, key, source, expires_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (principal, resource, key) DO UPDATE SET
	source     = excluded.source,
	expires_at = excluded.expires_at
`

type RecordGrantParams struct {
	Principal string
	Resource  string
	Key       string
	Source    string
	ExpiresAt int64
}

func (q *Queries) RecordGrant(ctx context.Context, arg RecordGrantParams) error {
	_, err := q.db.ExecContext(ctx, recordGrant,
		arg.Principal,
		arg.Resource,
		arg.Key,
		arg.Source,
		arg.ExpiresAt,
	)
	return err
}

const revokeGrant = `-- name: RevokeGrant :execrows
DELETE FROM mirror_grant WHERE principal = ? AND resource = ? AND key = ?
`

type RevokeGrantParams struct {
	Principal string
	Resource  string
	Key       string
}

func (q *Queries) RevokeGrant(ctx context.Context, arg RevokeGrantParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeGrant, arg.Principal, arg.Resource, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
