// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: freshness.sql

package dbgen

import (
	"context"
	"database/sql"
)

const deleteFreshness = `-- name: DeleteFreshness :execrows
DELETE FROM mirror_freshness WHERE kind = ? AND key = ?
`

type DeleteFreshnessParams struct {
	Kind string
	Key  string
}

func (q *Queries) DeleteFreshness(ctx context.Context, arg DeleteFreshnessParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFreshness, arg.Kind, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getFreshness = `-- name: GetFreshness :one
SELECT kind, "key", fetched_at, changed_at, etag, expires_at, state, error, retry_after, status FROM mirror_freshness WHERE kind = ? AND key = ?
`

type GetFreshnessParams struct {
	Kind string
	Key  string
}

func (q *Queries) GetFreshness(ctx context.Context, arg GetFreshnessParams) (MirrorFreshness, error) {
	row := q.db.QueryRowContext(ctx, getFreshness, arg.Kind, arg.Key)
	var i MirrorFreshness
	err := row.Scan(
		&i.Kind,
		&i.Key,
		&i.FetchedAt,
		&i.ChangedAt,
		&i.Etag,
		&i.ExpiresAt,
		&i.State,
		&i.Error,
		&i.RetryAfter,
		&i.Status,
	)
	return i, err
}

const markError = `-- name: MarkError :exec
INSERT INTO mirror_freshness (kind, key, state, error, retry_after)
VALUES (?, ?, 'error', ?, ?)
ON CONFLICT (kind, key) DO UPDATE SET
	state       = 'error',
	error       = excluded.error,
	retry_after = excluded.retry_after
`

type MarkErrorParams struct {
	Kind       string
	Key        string
	Error      string
	RetryAfter sql.NullInt64
}

func (q *Queries) MarkError(ctx context.Context, arg MarkErrorParams) error {
	_, err := q.db.ExecContext(ctx, markError,
		arg.Kind,
		arg.Key,
		arg.Error,
		arg.RetryAfter,
	)
	return err
}

const markFetching = `-- name: MarkFetching :exec
INSERT INTO mirror_freshness (kind, key, state) VALUES (?, ?, 'fetching')
ON CONFLICT (kind, key) DO UPDATE SET state = 'fetching'
`

type MarkFetchingParams struct {
	Kind string
	Key  string
}

// Every mark upserts. A first fetch has no row yet, and an UPDATE would report
// success while recording nothing.
func (q *Queries) MarkFetching(ctx context.Context, arg MarkFetchingParams) error {
	_, err := q.db.ExecContext(ctx, markFetching, arg.Kind, arg.Key)
	return err
}

const recordFetched = `-- name: RecordFetched :exec
INSERT INTO mirror_freshness (kind, key, fetched_at, changed_at, etag, expires_at, state, status, error, retry_after)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, '', NULL)
ON CONFLICT (kind, key) DO UPDATE SET
	fetched_at  = excluded.fetched_at,
	changed_at  = excluded.changed_at,
	etag        = excluded.etag,
	expires_at  = excluded.expires_at,
	state       = excluded.state,
	status      = excluded.status,
	error       = '',
	retry_after = NULL
`

type RecordFetchedParams struct {
	Kind      string
	Key       string
	FetchedAt sql.NullInt64
	ChangedAt sql.NullInt64
	Etag      string
	ExpiresAt sql.NullInt64
	State     string
	Status    int64
}

// A fetch that succeeded clears the error and the backoff with it. Leaving
// either behind holds off the next fetch on a failure that already healed.
func (q *Queries) RecordFetched(ctx context.Context, arg RecordFetchedParams) error {
	_, err := q.db.ExecContext(ctx, recordFetched,
		arg.Kind,
		arg.Key,
		arg.FetchedAt,
		arg.ChangedAt,
		arg.Etag,
		arg.ExpiresAt,
		arg.State,
		arg.Status,
	)
	return err
}
