// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type MirrorDeny struct {
	Principal string
	Resource  string
	Key       string
	Status    int64
	ExpiresAt int64
}

type MirrorFreshness struct {
	Kind       string
	Key        string
	FetchedAt  sql.NullInt64
	ChangedAt  sql.NullInt64
	Etag       string
	ExpiresAt  sql.NullInt64
	State      string
	Error      string
	RetryAfter sql.NullInt64
	Status     int64
}

type MirrorGrant struct {
	Principal string
	Resource  string
	Key       string
	Source    string
	ExpiresAt int64
}

type MirrorMetum struct {
	Key   string
	Value string
}

type MirrorWatermark struct {
	Subject   string
	AppliedAt int64
}
