// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watermark.sql

package dbgen

import (
	"context"
)

const applyWatermark = `-- name: ApplyWatermark :execrows
INSERT INTO mirror_watermark (subject, applied_at) VALUES (?, ?)
ON CONFLICT (subject) DO UPDATE SET applied_at = excluded.applied_at
WHERE excluded.applied_at >= mirror_watermark.applied_at
`

type ApplyWatermarkParams struct {
	Subject   string
	AppliedAt int64
}

// Applies only when the incoming view is at least as new as the stored one,
// and reports through the affected-row count whether it did.
//
// Equality MUST apply. A clock here is a second, and two genuinely distinct
// views of one subject land inside the same second all the time; refusing on
// equality drops the second one.
func (q *Queries) ApplyWatermark(ctx context.Context, arg ApplyWatermarkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyWatermark, arg.Subject, arg.AppliedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getWatermark = `-- name: GetWatermark :one
SELECT applied_at FROM mirror_watermark WHERE subject = ?
`

func (q *Queries) GetWatermark(ctx context.Context, subject string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getWatermark, subject)
	var applied_at int64
	err := row.Scan(&applied_at)
	return applied_at, err
}

const pruneWatermarks = `-- name: PruneWatermarks :execrows
DELETE FROM mirror_watermark WHERE applied_at < ?
`

func (q *Queries) PruneWatermarks(ctx context.Context, appliedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneWatermarks, appliedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
